name: Daily Contribution Graph Maintainer

on:
  schedule:
    # Runs everyday at 12:00 AM UTC
    - cron: '9 7 * * *'
  # Allows you to manually trigger the workflow anytime from the Actions tab
  workflow_dispatch: 

jobs:
  make-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create changes and Commit 5 times
        run: |
          git config --local user.email "your-github-email@example.com"
          git config --local user.name "Your GitHub Username"
          
          # Loop 5 times to generate 5 distinct commits
          for i in {1..5}
          do
            echo "Heartbeat $i: $(date)" > heartbeat.txt
            git add heartbeat.txt
            git commit -m "chore: daily heartbeat update $i [skip ci]"
          done

      - name: Push changes
        run: |
          git push
